In [4]:
import tensorflow

In [5]:
import torch

In [6]:
import torchvision

In [61]:
print(torch.cuda.is_available())

False


In [9]:
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [11]:
b = torch.tensor([[2,1,4], [3,5,4], [1,2,0], [4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [12]:
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [13]:
print(b.shape[0])

4


In [19]:
c = torch.FloatTensor([[2,1,4], [3,5,4], [1,2,0], [4,3,2]])

In [20]:
d = torch.DoubleTensor([[2,1,4], [3,5,4], [1,2,0], [4,3,2]])

In [21]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [22]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [23]:
print(c.mean())

tensor(2.5833)


In [24]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [25]:
print(c.std())

tensor(1.5050)


In [26]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [31]:
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))

b = b.view(1, -1)
print(b)
print(b.shape)
print('\n')

three_dim = torch.randn(2, 3, 4)
print('\n')

print(three_dim)
print(three_dim.view(2, 12))
print(three_dim.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])




tensor([[[ 1.4943, -1.7196,  0.0774,  0.7187],
         [ 0.2476, -0.4106, -0.4354,  0.7350],
         [ 0.3504,  1.4204, -1.4171,  0.3064]],

        [[ 0.7466, -0.5738,  0.0405, -0.2231],
         [ 1.9999, -0.1626, -1.4640, -0.5141],
         [-0.6642,  0.0606, -1.3082, -2.3458]]])
tensor([[ 1.4943, -1.7196,  0.0774,  0.7187,  0.2476, -0.4106, -0.4354,  0.7350,
          0.3504,  1.4204, -1.4171,  0.3064],
        [ 0.7466, -0.5738,  0.0405, -0.2231,  1.9999, -0.1626, -1.4640, -0.5141,
         -0.6642,  0.0606, -1.3082, -2.3458]])
tensor([[ 1.4943, -1.7196,  0.0774,  0.7187,  0.2476

In [33]:
r = torch.rand(4,4)
print(r)

tensor([[0.2980, 0.4337, 0.3914, 0.6383],
        [0.1221, 0.7610, 0.4714, 0.1293],
        [0.6512, 0.1889, 0.2051, 0.3956],
        [0.4022, 0.8676, 0.7527, 0.3445]])


In [34]:
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[-0.8041,  0.1807,  1.0576, -0.0981],
        [ 0.0382,  0.7090, -1.1765, -0.2994],
        [-0.3966,  1.1556, -0.0567, -1.5909],
        [-2.0137, -1.2230,  0.0558,  1.1616]])
torch.float32


In [47]:
in_array = torch.randint(6,20, (5,))
print(in_array)
print(in_array.dtype)

tensor([ 6, 12,  6,  6,  6])
torch.int64


In [55]:
in_array2 = torch.randint(6, 10, (3,3))
print(in_array2)

tensor([[6, 9, 6],
        [6, 6, 9],
        [8, 7, 9]])


In [56]:
print(torch.numel(in_array))

print(torch.numel(in_array2))

5
9


In [43]:
z = torch.zeros(3, 3, dtype = torch.long)
print(z)

o = torch.ones(3,3)
print(o)
print(o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [57]:
r2_like = torch.randn_like(r2, dtype = torch.double)
print(r2_like)

tensor([[ 0.1653, -0.4092, -0.1305,  0.7388],
        [ 2.1375,  1.0139, -0.5269, -1.0579],
        [-0.3843,  0.1692,  0.1619,  0.6173],
        [ 0.1676, -1.5023,  0.6990,  0.0188]], dtype=torch.float64)


In [58]:
add_result = torch.add(r, r2)
print(add_result)

tensor([[-0.5061,  0.6144,  1.4490,  0.5402],
        [ 0.1603,  1.4700, -0.7051, -0.1701],
        [ 0.2547,  1.3445,  0.1484, -1.1953],
        [-1.6115, -0.3555,  0.8085,  1.5062]])


In [59]:
r2.add_(r)
print(r2)

tensor([[-0.5061,  0.6144,  1.4490,  0.5402],
        [ 0.1603,  1.4700, -0.7051, -0.1701],
        [ 0.2547,  1.3445,  0.1484, -1.1953],
        [-1.6115, -0.3555,  0.8085,  1.5062]])


In [60]:
print(r2[:,1])
print(r2[:, :2])
print(r2[:3,:])
num_ten = r2[2,3]
print(num_ten)
print(num_ten.item())
print(r2[2, :])

tensor([ 0.6144,  1.4700,  1.3445, -0.3555])
tensor([[-0.5061,  0.6144],
        [ 0.1603,  1.4700],
        [ 0.2547,  1.3445],
        [-1.6115, -0.3555]])
tensor([[-0.5061,  0.6144,  1.4490,  0.5402],
        [ 0.1603,  1.4700, -0.7051, -0.1701],
        [ 0.2547,  1.3445,  0.1484, -1.1953]])
tensor(-1.1953)
-1.1952571868896484
tensor([ 0.2547,  1.3445,  0.1484, -1.1953])
